### ISSUE TITLE
File browser doesn't work 

### ISSUE THREAD

**Issue by Qu4tro** [pbu88/diffy#28]
Hey again.

The sidebar filebrowser doesn't seem to be working. 
By not working I mean: You can click it, it looks and behaves like a link, but it doesn't actually do nothing, leaving you only capable of seeing the diff of the first file.

I think it must be some issue with the current master? If so, it should be reproducible with the result docker setup from #27 . 
I've tried with FF/Chrome, private mode, etc, `diffy.org` works fine for me, so I don't think it's an issue on my side.

Thanks in advance.

**Comment by pbu88** [comment]
Hey, yes! Thanks for submitting this issue. This bug was introduced in the last patch. I detected it on production and rolled back the rollout but HEAD is still broken indeed. This happens because the angular component of the filetree is not being updated. It was a side effect of the bug I was trying to fix with the side scrolling being refreshed every second. The fix should be simple but I haven't had the time to add it :-/

**Comment by pbu88** [comment]
This should be fixed now.

**Comment by Qu4tro** [comment]
Awesome. Thanks!
