### ISSUE TITLE
An option to copy code without line numbers or +/-

### ISSUE THREAD

**Issue by edin-m** [pbu88/diffy#30]
Is there an option to copy the code (multi-line) without actually copying the +/- and line numbers?

If not, what's the best approach for implementing this?

**Comment by pbu88** [comment]
Hi @edin-m. There's no option currently to do that. A workaround would be to download the diff and copy it with any text editor on your local machine but I can see how that's cumbersome.

From top of my head, what do you think if there'd be a feature that would let you show on the UI the raw diff text so that you could copy the relevant bits right there without having to download? Bear in mind that this still would include the +/- because this is regular diff output.

**Comment by edin-m** [comment]
My use-case is selecting a chunk of code and copy-paste it in the IDE. Now I have to manually remove line numbers and +/-. If I review diff in a text editor and copy-paste again, I still need to remove +/-. Having an option to review a diff doesn't help much.

I imagine a button which would copy selected code to the clipboard without +/- at the start of the lines.

**Comment by pbu88** [comment]
I see. Will give it a thought at the UI.

**Comment by pbu88** [comment]
@edin-m I think this has been solved in https://github.com/pbu88/diffy/issues/53.
