### ISSUE TITLE
5 days limit is bad for a blog post

### ISSUE THREAD

**Issue by goooseman** [pbu88/diffy#51]
Hi!

I was looking for a service to embed my git diff as an iframe to a Medium article.
And your service is something I was really looking for! The UI is simple, looks good inside an iframe and I can use this site inside a Medium embed.

But this 5 days restriction is nothing for a blog post! Of course I can extend this day, but you know updating all the diffs I've ever published every 5 days will be a nightmare if done manually or will be difficult if done automatically (e.g. by writing a bot that will click the link).

What is the official opinion on this problem? I understand that we can not give a "this is a blog post, make the link permanent" checkbox, because it can be abused easily.

But anyway what's the problem to store everything forever? I do not like this idea either, but we are speaking about storing git diffs, they are extremely small and non-binary.

Maybe we can think about solution, that auto-cleanup items, which were not accessed at all for more then 2 years.

P.S. If custom development is required, I will be able to contribute to the repo. But first we need to agree on a strategy.

**Comment by pbu88** [comment]
Hi @goooseman, thank you very much for reaching out. I've always been curious in particular about this use case: the embedding feature. Coincidentally, another person reached out by email recently asking for the permanent Diffy feature. I want to enable this but I'd like to enable that only for users I can attribute them to. That'd require some sort of user account system, some simple OAuth integration where I'd only keep an email or the bare minimum to reach out the owner and notify them about their diffs.

I'm currently trying to set that up, however in the mean time it'd be fine to enable a "Make permanent" feature if the creator provides it's email or something (in the UI, I see it happening after several clicks to the "Extend Lifetime", then replace the text with "Make Permanent" and show a dialog to let the user introduce an email.

The email is important in this case because once the user account system is in place, I'd like to migrate those to their right users. I'll try to come up with that in the next couple of days to enable your use cases.

## Why not make them permanent without any attribution

I don't really want to do that because first, if I ever decide to give up on the tool, I want to let people that own permanent Diffy's know, because it potentially can break indeed their blog posts. I hope that never happens but you never know. Also, even though they are small, they are piling up every day and it's only gonna cost more and more.

## Summary

I will unblock this use case by making them permanent after a couple of "extensions" and a more future solution is gonna be accounts using OAuth. Help is of course appreciated, if you get acquainted with the code and submit a patch that'd be great but otherwise I can just do it quickly and then let's see how to enhance it afterwards.

I want to actually implement an Embed Diff source code so it does something similar that Github does "Hosted by Diffy.org" or something like that just to promote it a little bit, but in the mean time the iframe on Medium should work.

Let me know your thoughts.

Cheers!

**Comment by pbu88** [comment]
Hi @goooseman and @gabriel-kaam, I just submitted and rolled out a patch to allow for making a diff permanent, so it wont get deleted. The way it works is you click in "Extend lifetime" for a couple of times (5) and after that, it will show a "Make permanent" link instead of the "extend lifetime" one.

This is a temp solution to unblock you from what you were trying to do until I find the time to set up an account system and introduce proper ownership of permanent diffs. I have appreciated your feedback a lot, please keep it coming, as well as any ideas or use case that you'd like Diffy to support.

Here I made permanent the diff that actually got the work done: https://diffy.org/diff/1f852780d73c3. As you can see it doesn't show a countdown anymore because it won't get deleted.

Let me know your thoughts.
