### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by mwarkentin** [pbu88/diffy#69]
It would be nice to have keyboard shortcuts available for jumping through diffs / between files.

It'd be nice if I could navigate large diffs like this by just hitting Up / Down or other keys:

<img width="1716" alt="image" src="https://user-images.githubusercontent.com/67560/176751259-3ba94dd0-fdb3-4ebc-ba78-9f525334b970.png">

**Comment by pbu88** [comment]
Hi @mwarkentin , sorry for the delayed response I was on holidays. Aside from up and down, is there any other key shortcut you'd use? I'll try to come up with a POC for this.

**Comment by mwarkentin** [comment]
@pbu88 No worries. :) I think keyboard shortcuts for moving between files and between diffs in a single file (or maybe if you hit "next diff" at the end of one file it could move to the next file as well) would be the main ones.

**Comment by pbu88** [comment]
Hey, just a quick update about this. I started working on it. Nothing fancy, I think the easiest is to use "j" to go down and "k" to go up, inspired from vim. This is the first commit: https://github.com/pbu88/diffy/commit/1cb6af24748671ebabf507ded7d515689499674e. Currently is not very useful because the FileTree component is missing highlight logic for the current selected file. I want to add that before deploying this feature.

**Comment by pbu88** [comment]
Done. You can see it working here. Navigate with "j" or "k" keys. It's very basic but should work for your use case. If something else is needed I can iterate on it.

Thanks for using diffy :-) Please share if there's any other feedback or features you'd like to make it more useful.
